FROM golang:1.24.2 AS builder

WORKDIR /app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o weatherapi .


# Stage 2: Run
FROM alpine:3.22  

WORKDIR /root/

# Copy binary từ builder
COPY --from=builder /app/weatherapi .

# Set biến môi trường
ENV PORT=8080


# Expose port
EXPOSE 8080

# Run app
CMD ["./weatherapi"]